/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminGlobalRolesIndexRouteImport } from './routes/_authenticated/admin/global-roles/index'
import { Route as AuthenticatedProjectsProjectIdTeamIndexRouteImport } from './routes/_authenticated/projects/$projectId/team/index'
import { Route as AuthenticatedProjectsProjectIdSettingsIndexRouteImport } from './routes/_authenticated/projects/$projectId/settings/index'
import { Route as AuthenticatedProjectsProjectIdIntegrationsIndexRouteImport } from './routes/_authenticated/projects/$projectId/integrations/index'
import { Route as AuthenticatedProjectsProjectIdDocsIndexRouteImport } from './routes/_authenticated/projects/$projectId/docs/index'
import { Route as AuthenticatedProjectsProjectIdTasksTaskIdRouteImport } from './routes/_authenticated/projects/$projectId/tasks/$taskId'
import { Route as AuthenticatedProjectsProjectIdIntegrationsBacklogRouteImport } from './routes/_authenticated/projects/$projectId/integrations/backlog'
import { Route as AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRouteImport } from './routes/_authenticated/projects/$projectId/integrations/sprints/$sprintId'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGlobalRolesIndexRoute =
  AuthenticatedAdminGlobalRolesIndexRouteImport.update({
    id: '/admin/global-roles/',
    path: '/admin/global-roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTeamIndexRoute =
  AuthenticatedProjectsProjectIdTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsIndexRoute =
  AuthenticatedProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdIntegrationsIndexRoute =
  AuthenticatedProjectsProjectIdIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocsIndexRoute =
  AuthenticatedProjectsProjectIdDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksTaskIdRoute =
  AuthenticatedProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdIntegrationsBacklogRoute =
  AuthenticatedProjectsProjectIdIntegrationsBacklogRouteImport.update({
    id: '/integrations/backlog',
    path: '/integrations/backlog',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute =
  AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRouteImport.update({
    id: '/integrations/sprints/$sprintId',
    path: '/integrations/sprints/$sprintId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/integrations/backlog': typeof AuthenticatedProjectsProjectIdIntegrationsBacklogRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/integrations/': typeof AuthenticatedProjectsProjectIdIntegrationsIndexRoute
  '/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/integrations/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/global-roles': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/integrations/backlog': typeof AuthenticatedProjectsProjectIdIntegrationsBacklogRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/projects/$projectId/docs': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/integrations': typeof AuthenticatedProjectsProjectIdIntegrationsIndexRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/integrations/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/integrations/backlog': typeof AuthenticatedProjectsProjectIdIntegrationsBacklogRoute
  '/_authenticated/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/_authenticated/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/_authenticated/projects/$projectId/integrations/': typeof AuthenticatedProjectsProjectIdIntegrationsIndexRoute
  '/_authenticated/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/_authenticated/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/_authenticated/projects/$projectId/integrations/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/projects/$projectId'
    | '/home/'
    | '/profile/'
    | '/admin/global-roles/'
    | '/admin/users/'
    | '/projects/$projectId/'
    | '/projects/$projectId/integrations/backlog'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/docs/'
    | '/projects/$projectId/integrations/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/team/'
    | '/projects/$projectId/integrations/sprints/$sprintId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/home'
    | '/profile'
    | '/admin/global-roles'
    | '/admin/users'
    | '/projects/$projectId'
    | '/projects/$projectId/integrations/backlog'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/docs'
    | '/projects/$projectId/integrations'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/team'
    | '/projects/$projectId/integrations/sprints/$sprintId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/home/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/global-roles/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/integrations/backlog'
    | '/_authenticated/projects/$projectId/tasks/$taskId'
    | '/_authenticated/projects/$projectId/docs/'
    | '/_authenticated/projects/$projectId/integrations/'
    | '/_authenticated/projects/$projectId/settings/'
    | '/_authenticated/projects/$projectId/team/'
    | '/_authenticated/projects/$projectId/integrations/sprints/$sprintId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/global-roles/': {
      id: '/_authenticated/admin/global-roles/'
      path: '/admin/global-roles'
      fullPath: '/admin/global-roles/'
      preLoaderRoute: typeof AuthenticatedAdminGlobalRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/team/': {
      id: '/_authenticated/projects/$projectId/team/'
      path: '/team'
      fullPath: '/projects/$projectId/team/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings/': {
      id: '/_authenticated/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/integrations/': {
      id: '/_authenticated/projects/$projectId/integrations/'
      path: '/integrations'
      fullPath: '/projects/$projectId/integrations/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/docs/': {
      id: '/_authenticated/projects/$projectId/docs/'
      path: '/docs'
      fullPath: '/projects/$projectId/docs/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks/$taskId': {
      id: '/_authenticated/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/integrations/backlog': {
      id: '/_authenticated/projects/$projectId/integrations/backlog'
      path: '/integrations/backlog'
      fullPath: '/projects/$projectId/integrations/backlog'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIntegrationsBacklogRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/integrations/sprints/$sprintId': {
      id: '/_authenticated/projects/$projectId/integrations/sprints/$sprintId'
      path: '/integrations/sprints/$sprintId'
      fullPath: '/projects/$projectId/integrations/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdIntegrationsBacklogRoute: typeof AuthenticatedProjectsProjectIdIntegrationsBacklogRoute
  AuthenticatedProjectsProjectIdTasksTaskIdRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  AuthenticatedProjectsProjectIdDocsIndexRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  AuthenticatedProjectsProjectIdIntegrationsIndexRoute: typeof AuthenticatedProjectsProjectIdIntegrationsIndexRoute
  AuthenticatedProjectsProjectIdSettingsIndexRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  AuthenticatedProjectsProjectIdTeamIndexRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute: typeof AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdIntegrationsBacklogRoute:
      AuthenticatedProjectsProjectIdIntegrationsBacklogRoute,
    AuthenticatedProjectsProjectIdTasksTaskIdRoute:
      AuthenticatedProjectsProjectIdTasksTaskIdRoute,
    AuthenticatedProjectsProjectIdDocsIndexRoute:
      AuthenticatedProjectsProjectIdDocsIndexRoute,
    AuthenticatedProjectsProjectIdIntegrationsIndexRoute:
      AuthenticatedProjectsProjectIdIntegrationsIndexRoute,
    AuthenticatedProjectsProjectIdSettingsIndexRoute:
      AuthenticatedProjectsProjectIdSettingsIndexRoute,
    AuthenticatedProjectsProjectIdTeamIndexRoute:
      AuthenticatedProjectsProjectIdTeamIndexRoute,
    AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute:
      AuthenticatedProjectsProjectIdIntegrationsSprintsSprintIdRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedAdminGlobalRolesIndexRoute: typeof AuthenticatedAdminGlobalRolesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedAdminGlobalRolesIndexRoute:
    AuthenticatedAdminGlobalRolesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
